spring:
  datasource:
    url: jdbc:mysql://localhost:3306/domestic_transactions
    username: dombimihaly89
    password: Dina*Maki0307
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: 'create-drop'
